package nfl

import "github.com/jmeyers35/slate/pkg/espn/client"

const (
	TeamIDArizonaCardinals     client.TeamID = "22"
	TeamIDAtlantaFalcons       client.TeamID = "1"
	TeamIDBaltimoreRavens      client.TeamID = "33"
	TeamIDBuffaloBills         client.TeamID = "2"
	TeamIDCarolinaPanthers     client.TeamID = "29"
	TeamIDChicagoBears         client.TeamID = "3"
	TeamIDCincinnatiBengals    client.TeamID = "4"
	TeamIDClevelandBrowns      client.TeamID = "5"
	TeamIDDallasCowboys        client.TeamID = "6"
	TeamIDDenverBroncos        client.TeamID = "7"
	TeamIDDetroitLions         client.TeamID = "8"
	TeamIDGreenBayPackers      client.TeamID = "9"
	TeamIDHoustonTexans        client.TeamID = "34"
	TeamIDIndianapolisColts    client.TeamID = "11"
	TeamIDJacksonvilleJaguars  client.TeamID = "30"
	TeamIDKansasCityChiefs     client.TeamID = "12"
	TeamIDLasVegasRaiders      client.TeamID = "13"
	TeamIDLosAngelesChargers   client.TeamID = "24"
	TeamIDLosAngelesRams       client.TeamID = "14"
	TeamIDMiamiDolphins        client.TeamID = "15"
	TeamIDMinnesotaVikings     client.TeamID = "16"
	TeamIDNewEnglandPatriots   client.TeamID = "17"
	TeamIDNewOrleansSaints     client.TeamID = "18"
	TeamIDNewYorkGiants        client.TeamID = "19"
	TeamIDNewYorkJets          client.TeamID = "20"
	TeamIDPhiladelphiaEagles   client.TeamID = "21"
	TeamIDPittsburghSteelers   client.TeamID = "23"
	TeamIDSanFrancisco49ers    client.TeamID = "25"
	TeamIDSeattleSeahawks      client.TeamID = "26"
	TeamIDTampaBayBuccaneers   client.TeamID = "27"
	TeamIDTennesseeTitans      client.TeamID = "10"
	TeamIDWashingtonCommanders client.TeamID = "28"
)
